### ISSUE TITLE
requires a generator function

### ISSUE THREAD

**Issue by Diokuz** [ivpusic/koa-bunyan#3]
```bash
assert.js:90
  throw new assert.AssertionError({
  ^
AssertionError: app.use() requires a generator function
    at Application.app.use (/Users/dm.kuznetsov/github/backsquare/node_modules/koa/lib/application.js:106:5)
    at Object.<anonymous> (/Users/dm.kuznetsov/github/backsquare/app.js:22:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/dm.kuznetsov/github/backsquare/server.js:7:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3

```

"koa-bunyan": "^1.0.0",
"koa": "^1.2.0",
"bunyan": "^1.8.0",

**Comment by ivpusic** [comment]
1.0 supports koa2. use version < 1 for koa 1
